apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dpa-minio
  namespace: argocd
spec:
  project: dpa-guard
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: 17.0.21
    helm:
      releaseName: minio
      values: |
        mode: standalone

        auth:
          existingSecret: minio-creds
          rootUser: rootUser
          rootPassword: rootPassword

        defaultBuckets: "dpa-guard"

        persistence:
          enabled: false

        service:
          type: ClusterIP

        image:
          registry: docker.io
          repository: bitnamilegacy/minio
          tag: 2025.7.23-debian-12-r3

        clientImage:
          registry: docker.io
          repository: bitnamilegacy/minio-client
          tag: 2025.7.21-debian-12-r2

        console:
          image:
            registry: docker.io
            repository: bitnamilegacy/minio-object-browser
            tag: 2.0.2-debian-12-r3
  destination:
    server: https://kubernetes.default.svc
    namespace: dpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true