apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dpa-postgres
  namespace: argocd
spec:
  project: dpa-guard
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.2.0
    helm:
      releaseName: postgresql    
      values: |
        architecture: standalone

        auth:
          existingSecret: dpa-api-secrets
          username: DPA_DB_USER
          password: DPA_DB_PASSWORD
          database: dpa_guard

        primary:
          persistence:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true