apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dpa-redis
  namespace: argocd
spec:
  project: dpa-guard
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: "17.9.3"
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: dpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true