apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dpa-secrets
  namespace: argocd
spec:
  project: dpa-guard
  source:
    repoURL: https://github.com/skalej/dpa-guard.git
    targetRevision: main
    path: infra/k8s/secrets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true